
services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - .data/mongodb:/data/db
    tty: true
    restart: always

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    volumes:
      - .data/postgres_db:/data/db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: application
    tty: true
